language: objective-c
osx_image: xcode8.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - IOS_SIMULATOR_SDK=iphonesimulator10.1
    - IOS_SDK=iphoneos10.1
    - PROJECT_DIR=`pwd`
  matrix:
    - DESTINATION="OS=10.1,name=iPhone 7 Plus"  POD_LINT="YES"  $SDK="$IOS_SIMULATOR_SDK"
  before_install:
  - gem install cocoapods -v '1.1.0' --no-document
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - pod --version
  - pwd
  - cd $PROJECT_DIR/Tests;
  - pwd;
  - pod install;
  - xcodebuild -workspace SimpleFuturesTests.xcworkspace -scheme SimpleFuturesTests -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES build test | xcpretty -c;

